[tool.poetry]
name = "space_invaders"
version = "0.1.0"
description = ""
authors = ["CodinEric"]

[tool.poetry.dependencies]
python = "^3.9"
pygame = "^2.1.2"
numpy = "^1.22.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
